TENOS_DARK_BLUE_BG = "#0B1220"
TENOS_MEDIUM_BLUE_ACCENT = "#2563EB"
TENOS_LIGHT_BLUE_ACCENT2 = "#38BDF8"
TENOS_WHITE_FG = "#F8FAFC"
TENOS_BLACK_DETAIL = "#020617"

DOMINANT_BG = "#0F172A"
WIDGET_BG = "#111C3A"
TEXT_COLOR_NORMAL = TENOS_WHITE_FG
TEXT_COLOR_DISABLED = "#64748B"
BACKGROUND_COLOR = DOMINANT_BG
FRAME_BG_COLOR = WIDGET_BG
CANVAS_BG_COLOR = "#0B1220"
ENTRY_BG_COLOR = "#1E293B"
ENTRY_FG_COLOR = TEXT_COLOR_NORMAL
ENTRY_INSERT_COLOR = TENOS_LIGHT_BLUE_ACCENT2
SELECT_BG_COLOR = TENOS_MEDIUM_BLUE_ACCENT
SELECT_FG_COLOR = TEXT_COLOR_NORMAL
BUTTON_BG_COLOR = "#1E293B"
BUTTON_FG_COLOR = TEXT_COLOR_NORMAL
BUTTON_ACTIVE_BG_COLOR = TENOS_MEDIUM_BLUE_ACCENT
BUTTON_ACTIVE_FG_COLOR = TEXT_COLOR_NORMAL
BORDER_COLOR = TENOS_MEDIUM_BLUE_ACCENT
SCROLLBAR_TROUGH_COLOR = "#1E293B"
SCROLLBAR_SLIDER_COLOR = TENOS_MEDIUM_BLUE_ACCENT
LISTBOX_BG = ENTRY_BG_COLOR
LISTBOX_FG = ENTRY_FG_COLOR
LISTBOX_SELECT_BG = SELECT_BG_COLOR
LISTBOX_SELECT_FG = SELECT_FG_COLOR

ACTIVE_TAB_BG = ENTRY_BG_COLOR
INACTIVE_TAB_BG = "#15213B"
ACTIVE_TAB_FG = TEXT_COLOR_NORMAL
INACTIVE_TAB_FG = "#94A3B8"

LOG_STDOUT_FG = TENOS_LIGHT_BLUE_ACCENT2
LOG_STDERR_FG = "#F87171"
LOG_INFO_FG = TENOS_LIGHT_BLUE_ACCENT2
LOG_WORKER_FG = "#34D399"

BOLD_TLABEL_STYLE = "Bold.TLabel"
ACCENT_TLABEL_STYLE = "Accent.TLabel"

CONFIG_FILE_NAME = "config.json"
SETTINGS_FILE_NAME = "settings.json"
STYLES_CONFIG_FILE_NAME = "styles_config.json"
LLM_MODELS_FILE_NAME = "llm_models.json"
LLM_PROMPTS_FILE_NAME = "llm_prompts.json"
MODELS_LIST_FILE_NAME = "modelslist.json"
CHECKPOINTS_LIST_FILE_NAME = "checkpointslist.json"
CLIP_LIST_FILE_NAME = "cliplist.json"

ICON_PATH_ICO = r"tenos-ai_icon.ico"
ICON_PATH_PNG = r"tenos-ai_icon.png"

BOT_SCRIPT_NAME = "main_bot.py"
