TENOS_DARK_BLUE_BG = "#023373"
TENOS_MEDIUM_BLUE_ACCENT = "#0487D9"
TENOS_LIGHT_BLUE_ACCENT2 = "#7FB2F0"
TENOS_WHITE_FG = "#FFFFFF"
TENOS_BLACK_DETAIL = "#000000"

DOMINANT_BG = "#5f5f5f"
WIDGET_BG = "#404040"
TEXT_COLOR_NORMAL = TENOS_WHITE_FG
TEXT_COLOR_DISABLED = "#888888"
BACKGROUND_COLOR = DOMINANT_BG
FRAME_BG_COLOR = DOMINANT_BG
CANVAS_BG_COLOR = DOMINANT_BG
ENTRY_BG_COLOR = WIDGET_BG
ENTRY_FG_COLOR = TEXT_COLOR_NORMAL
ENTRY_INSERT_COLOR = TEXT_COLOR_NORMAL
SELECT_BG_COLOR = TENOS_MEDIUM_BLUE_ACCENT
SELECT_FG_COLOR = TEXT_COLOR_NORMAL
BUTTON_BG_COLOR = "#3f3f3f"
BUTTON_FG_COLOR = TEXT_COLOR_NORMAL
BUTTON_ACTIVE_BG_COLOR = TENOS_LIGHT_BLUE_ACCENT2
BUTTON_ACTIVE_FG_COLOR = TENOS_DARK_BLUE_BG
BORDER_COLOR = TENOS_MEDIUM_BLUE_ACCENT
SCROLLBAR_TROUGH_COLOR = "#3a3a3a"
SCROLLBAR_SLIDER_COLOR = TENOS_MEDIUM_BLUE_ACCENT
LISTBOX_BG = WIDGET_BG
LISTBOX_FG = ENTRY_FG_COLOR
LISTBOX_SELECT_BG = SELECT_BG_COLOR
LISTBOX_SELECT_FG = SELECT_FG_COLOR

ACTIVE_TAB_BG = "#5f5f5f"
INACTIVE_TAB_BG = "#3f3f3f"
ACTIVE_TAB_FG = TEXT_COLOR_NORMAL
INACTIVE_TAB_FG = "#b0b0b0"

LOG_STDOUT_FG = TEXT_COLOR_NORMAL
LOG_STDERR_FG = TENOS_LIGHT_BLUE_ACCENT2
LOG_INFO_FG = TENOS_LIGHT_BLUE_ACCENT2
LOG_WORKER_FG = TENOS_MEDIUM_BLUE_ACCENT

BOLD_TLABEL_STYLE = "Bold.TLabel"
ACCENT_TLABEL_STYLE = "Accent.TLabel"

CONFIG_FILE_NAME = "config.json"
SETTINGS_FILE_NAME = "settings.json"
STYLES_CONFIG_FILE_NAME = "styles_config.json"
LLM_MODELS_FILE_NAME = "llm_models.json"
LLM_PROMPTS_FILE_NAME = "llm_prompts.json"
MODELS_LIST_FILE_NAME = "modelslist.json"
CHECKPOINTS_LIST_FILE_NAME = "checkpointslist.json"
CLIP_LIST_FILE_NAME = "cliplist.json"

ICON_PATH_ICO = r"tenos-ai_icon.ico"
ICON_PATH_PNG = r"tenos-ai_icon.png"

BOT_SCRIPT_NAME = "main_bot.py"
