"""Node identifiers shared across Tenos.AI ComfyUI workflow templates."""

# FLUX Workflow Node IDs
GENERATION_MODEL_NODE = "1"
VARIATION_MODEL_NODE = "1"
UPSCALE_MODEL_NODE = "8:0"

GENERATION_WORKFLOW_STEPS_NODE = "8"
VARIATION_WORKFLOW_STEPS_NODE = "7"

GENERATION_CLIP_NODE = "2"
VARIATION_CLIP_NODE = "2"
UPSCALE_CLIP_NODE = "8:1"

PROMPT_LORA_NODE = "10"
IMG2IMG_LORA_NODE = "17"
UPSCALE_LORA_NODE = "116"
VARY_LORA_NODE = "35"
FLUX_VAR_BATCH_NODE = "var_batcher"

GENERATION_LATENT_NODE = "99"
UPSCALE_HELPER_LATENT_NODE = "98"

# SDXL Workflow Node IDs
SDXL_CHECKPOINT_LOADER_NODE = "sdxl_1"
SDXL_LORA_NODE = "sdxl_lora"
SDXL_CLIP_SKIP_NODE = "sdxl_2"
SDXL_POS_PROMPT_NODE = "sdxl_3"
SDXL_NEG_PROMPT_NODE = "sdxl_4"
SDXL_KSAMPLER_NODE = "sdxl_5"
SDXL_VAE_DECODE_NODE = "sdxl_6"
SDXL_SAVE_IMAGE_NODE = "sdxl_7"
SDXL_LATENT_NODE = "sdxl_8"

# SDXL Img2Img specific node IDs
SDXL_IMG2IMG_LOAD_IMAGE_NODE = "sdxl_i2i_load"
SDXL_IMG2IMG_RESIZE_NODE = "sdxl_i2i_resize"
SDXL_IMG2IMG_VAE_ENCODE_NODE = "sdxl_i2i_vae_encode"

SDXL_VAR_LOAD_IMAGE_NODE = "sdxl_var_load"
SDXL_VAR_RESIZE_NODE = "sdxl_var_resize"
SDXL_VAR_VAE_ENCODE_NODE = "sdxl_var_vae_encode"
SDXL_VAR_CLIP_SKIP_NODE = "sdxl_var_clip_skip"
SDXL_VAR_LORA_NODE = SDXL_LORA_NODE  # Reusing
SDXL_VAR_POS_PROMPT_NODE = "sdxl_var_pos_prompt"
SDXL_VAR_NEG_PROMPT_NODE = "sdxl_var_neg_prompt"
SDXL_VAR_KSAMPLER_NODE = "sdxl_var_ksampler"
SDXL_VAR_VAE_DECODE_NODE = "sdxl_var_vae_decode"
SDXL_VAR_SAVE_IMAGE_NODE = "sdxl_var_save_image"
SDXL_VAR_BATCH_NODE = "sdxl_var_batcher"

SDXL_UPSCALE_LOAD_IMAGE_NODE = "sdxl_up_load"
SDXL_UPSCALE_MODEL_LOADER_NODE = "sdxl_up_model_loader"
SDXL_UPSCALE_ULTIMATE_NODE = "sdxl_up_ultimate"
SDXL_UPSCALE_HELPER_LATENT_NODE = "sdxl_up_helper_latent"
SDXL_UPSCALE_SAVE_IMAGE_NODE = "sdxl_up_save"
SDXL_UPSCALE_LORA_NODE = SDXL_LORA_NODE  # Reusing
SDXL_UPSCALE_CLIP_SKIP_NODE = "sdxl_upscale_clip_skip"
SDXL_UPSCALE_POS_PROMPT_NODE = "sdxl_upscale_pos_prompt"
SDXL_UPSCALE_NEG_PROMPT_NODE = "sdxl_upscale_neg_prompt"

# Qwen Image Workflow Node IDs
QWEN_CHECKPOINT_LOADER_NODE = "qwen_ckpt"
QWEN_LORA_NODE = "qwen_lora"
QWEN_CLIP_SKIP_NODE = "qwen_clip_skip"
QWEN_POS_PROMPT_NODE = "qwen_pos_prompt"
QWEN_NEG_PROMPT_NODE = "qwen_neg_prompt"
QWEN_KSAMPLER_NODE = "qwen_ksampler"
QWEN_VAE_DECODE_NODE = "qwen_vae_decode"
QWEN_SAVE_IMAGE_NODE = "qwen_save"
QWEN_LATENT_NODE = "qwen_latent"

QWEN_IMG2IMG_LOAD_IMAGE_NODE = "qwen_i2i_load"
QWEN_IMG2IMG_RESIZE_NODE = "qwen_i2i_resize"
QWEN_IMG2IMG_VAE_ENCODE_NODE = "qwen_i2i_vae_encode"

QWEN_VAR_LOAD_IMAGE_NODE = "qwen_var_load"
QWEN_VAR_RESIZE_NODE = "qwen_var_resize"
QWEN_VAR_VAE_ENCODE_NODE = "qwen_var_vae_encode"
QWEN_VAR_CLIP_SKIP_NODE = QWEN_CLIP_SKIP_NODE
QWEN_VAR_LORA_NODE = QWEN_LORA_NODE
QWEN_VAR_POS_PROMPT_NODE = "qwen_var_pos_prompt"
QWEN_VAR_NEG_PROMPT_NODE = "qwen_var_neg_prompt"
QWEN_VAR_KSAMPLER_NODE = "qwen_var_ksampler"
QWEN_VAR_VAE_DECODE_NODE = "qwen_var_vae_decode"
QWEN_VAR_SAVE_IMAGE_NODE = "qwen_var_save"
QWEN_VAR_BATCH_NODE = "qwen_var_batch"

QWEN_UPSCALE_LOAD_IMAGE_NODE = "qwen_up_load"
QWEN_UPSCALE_MODEL_LOADER_NODE = "qwen_up_model_loader"
QWEN_UPSCALE_HELPER_LATENT_NODE = "qwen_up_helper_latent"
QWEN_UPSCALE_SAVE_IMAGE_NODE = "qwen_up_save"
QWEN_UPSCALE_LORA_NODE = QWEN_LORA_NODE
QWEN_UPSCALE_CLIP_SKIP_NODE = "qwen_up_clip_skip"
QWEN_UPSCALE_POS_PROMPT_NODE = "qwen_up_pos_prompt"
QWEN_UPSCALE_NEG_PROMPT_NODE = "qwen_up_neg_prompt"
QWEN_UPSCALE_ULTIMATE_NODE = "qwen_up_ultimate"


__all__ = [
    "GENERATION_MODEL_NODE",
    "VARIATION_MODEL_NODE",
    "UPSCALE_MODEL_NODE",
    "GENERATION_WORKFLOW_STEPS_NODE",
    "VARIATION_WORKFLOW_STEPS_NODE",
    "GENERATION_CLIP_NODE",
    "VARIATION_CLIP_NODE",
    "UPSCALE_CLIP_NODE",
    "PROMPT_LORA_NODE",
    "IMG2IMG_LORA_NODE",
    "UPSCALE_LORA_NODE",
    "VARY_LORA_NODE",
    "FLUX_VAR_BATCH_NODE",
    "GENERATION_LATENT_NODE",
    "UPSCALE_HELPER_LATENT_NODE",
    "SDXL_CHECKPOINT_LOADER_NODE",
    "SDXL_LORA_NODE",
    "SDXL_CLIP_SKIP_NODE",
    "SDXL_POS_PROMPT_NODE",
    "SDXL_NEG_PROMPT_NODE",
    "SDXL_KSAMPLER_NODE",
    "SDXL_VAE_DECODE_NODE",
    "SDXL_SAVE_IMAGE_NODE",
    "SDXL_LATENT_NODE",
    "SDXL_IMG2IMG_LOAD_IMAGE_NODE",
    "SDXL_IMG2IMG_RESIZE_NODE",
    "SDXL_IMG2IMG_VAE_ENCODE_NODE",
    "SDXL_VAR_LOAD_IMAGE_NODE",
    "SDXL_VAR_RESIZE_NODE",
    "SDXL_VAR_VAE_ENCODE_NODE",
    "SDXL_VAR_CLIP_SKIP_NODE",
    "SDXL_VAR_LORA_NODE",
    "SDXL_VAR_POS_PROMPT_NODE",
    "SDXL_VAR_NEG_PROMPT_NODE",
    "SDXL_VAR_KSAMPLER_NODE",
    "SDXL_VAR_VAE_DECODE_NODE",
    "SDXL_VAR_SAVE_IMAGE_NODE",
    "SDXL_VAR_BATCH_NODE",
    "SDXL_UPSCALE_LOAD_IMAGE_NODE",
    "SDXL_UPSCALE_MODEL_LOADER_NODE",
    "SDXL_UPSCALE_ULTIMATE_NODE",
    "SDXL_UPSCALE_HELPER_LATENT_NODE",
    "SDXL_UPSCALE_SAVE_IMAGE_NODE",
    "SDXL_UPSCALE_LORA_NODE",
    "SDXL_UPSCALE_CLIP_SKIP_NODE",
    "SDXL_UPSCALE_POS_PROMPT_NODE",
    "SDXL_UPSCALE_NEG_PROMPT_NODE",
    "QWEN_CHECKPOINT_LOADER_NODE",
    "QWEN_LORA_NODE",
    "QWEN_CLIP_SKIP_NODE",
    "QWEN_POS_PROMPT_NODE",
    "QWEN_NEG_PROMPT_NODE",
    "QWEN_KSAMPLER_NODE",
    "QWEN_VAE_DECODE_NODE",
    "QWEN_SAVE_IMAGE_NODE",
    "QWEN_LATENT_NODE",
    "QWEN_IMG2IMG_LOAD_IMAGE_NODE",
    "QWEN_IMG2IMG_RESIZE_NODE",
    "QWEN_IMG2IMG_VAE_ENCODE_NODE",
    "QWEN_VAR_LOAD_IMAGE_NODE",
    "QWEN_VAR_RESIZE_NODE",
    "QWEN_VAR_VAE_ENCODE_NODE",
    "QWEN_VAR_CLIP_SKIP_NODE",
    "QWEN_VAR_LORA_NODE",
    "QWEN_VAR_POS_PROMPT_NODE",
    "QWEN_VAR_NEG_PROMPT_NODE",
    "QWEN_VAR_KSAMPLER_NODE",
    "QWEN_VAR_VAE_DECODE_NODE",
    "QWEN_VAR_SAVE_IMAGE_NODE",
    "QWEN_VAR_BATCH_NODE",
    "QWEN_UPSCALE_LOAD_IMAGE_NODE",
    "QWEN_UPSCALE_MODEL_LOADER_NODE",
    "QWEN_UPSCALE_HELPER_LATENT_NODE",
    "QWEN_UPSCALE_SAVE_IMAGE_NODE",
    "QWEN_UPSCALE_LORA_NODE",
    "QWEN_UPSCALE_CLIP_SKIP_NODE",
    "QWEN_UPSCALE_POS_PROMPT_NODE",
    "QWEN_UPSCALE_NEG_PROMPT_NODE",
    "QWEN_UPSCALE_ULTIMATE_NODE",
]
